# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F2 < Formula
  desc "F2 is a cross-platform command-line tool for batch renaming files and directories quickly and safely"
  homepage "https://f2.freshman.tech"
  version "2.2.2"

  depends_on "exiftool" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.2/f2_2.2.2_darwin_amd64.tar.gz"
      sha256 "2a037a55f25ee6c083af38ce3aafce885ecedfb13b17c867c2dc930320b5fae5"

      def install
        bin.install "f2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.2/f2_2.2.2_darwin_arm64.tar.gz"
      sha256 "18d7cf76719b335b1b12ec7605b89637d6d832ec196beca9a0436e270252dd8c"

      def install
        bin.install "f2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.2/f2_2.2.2_linux_amd64.tar.gz"
      sha256 "d44bca9d9a08721655e0fd4a3459f4c2b844abb896de3e6a74551e8bf5f51432"
      def install
        bin.install "f2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.2/f2_2.2.2_linux_arm64.tar.gz"
      sha256 "65a38d8fe73a386d86f5163235ba3df04fc6cd45f73a6f67bf90ea02f1b9abfd"
      def install
        bin.install "f2"
      end
    end
  end
end
