# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F2 < Formula
  desc "F2 is a cross-platform command-line tool for batch renaming files and directories quickly and safely"
  homepage "https://f2.freshman.tech"
  version "2.2.0"

  depends_on "exiftool" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.0/f2_2.2.0_darwin_amd64.tar.gz"
      sha256 "b9a2b8f58f96991f4d4bc08cdfe66cd9f46d17573b00f9e48889991c2ad01957"

      def install
        bin.install "f2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.0/f2_2.2.0_darwin_arm64.tar.gz"
      sha256 "66f6931ccaa6612ae05f7adb240a58f4de25e97e498d3dcad6dc285429eafb10"

      def install
        bin.install "f2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.0/f2_2.2.0_linux_amd64.tar.gz"
      sha256 "03d41c18d8bd86662ae16c4b3deeac2f782b2043f611d8baee9b3858538ff905"
      def install
        bin.install "f2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayoisaiah/f2/releases/download/v2.2.0/f2_2.2.0_linux_arm64.tar.gz"
      sha256 "17c689736ffc39278a3efaf27cd8a987bf7f1f40efaa84e2388bb8ac9baf45f5"
      def install
        bin.install "f2"
      end
    end
  end
end
